version: '3'
services:
  mysql-container:
    image: mysql
    container_name: mysql-container
    restart: always
    networks:
      - traceable-network
    environment:
      MYSQL_DATABASE: "Traceable"
      MYSQL_ROOT_PASSWORD: "Password"
    ports:
      - "3307:3306"
    volumes:
      - traceable-db:/var/lib/mysql

  traceable-container:
    image: "traceable-image"
    container_name: traceable-container
    restart: always
    networks:
      - traceable-network
    ports:
      - "8081:8081"
    depends_on:
      - mysql-container

networks:
  traceable-network:
    driver: bridge

volumes:
  traceable-db: